<?php

namespace rasel9w9\DataGenerator;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
class GenerateDataCommand extends Command
{
    protected $signature = 'alauddin:generate-data';
    protected $description = 'To Generate All Data As Array';
    public function __construct(){
        parent::__construct();
    }

    public function handle(){
        ini_set('memory_limit', '-1');
        ini_set('max_execution_time', 0);
        $connection = DB::getPdo();
		$phpFile = "<?php \n";
        $phpFile .= "/* \nData Generated By Md. Alauddin.\nDate&Time: ".date("d-M-Y h-i-s")."\n";
        $phpFile .= "Contact: email:rasel9w9@gmail.com,Phone:01817241707,01517189226\n";
        $phpFile .= "\t--IsDB BISEW Round 42(WDPF NVIT) \n*/ \n\n";
        if(PHP_SAPI=="cli"){
            echo "$table Data are exporting...\n\n";
            $this->output->progressStart(1);
        }
        $connection = DB::getPdo();
        $result = $connection->query("SELECT * FROM $table");
        $data = $result->fetchall(\PDO::FETCH_ASSOC);
        $phpFile.= "\$$table = ".var_export($data,true).";\n\n";
        $connection = null;
        file_put_contents(base_path("database/seeders/data")."/$table",$phpFile);
        if(PHP_SAPI=='cli'){
            $this->output->progressAdvance();
            $this->output->progressFinish();
            echo "$table Successfully Exported \n";
        }
    }
}
